# Core Colors
background            #11140f
foreground            #e1e4da
selection_foreground  #a8d292
selection_background  #153808
cursor                #a8d292
cursor_text_color     #11140f

# Regular Colors
color0  #11140f
color1  #ffb4ab
color2  #a8d292
color3  #a0cfd0
color4  #c3efac
color5  #d8e7cb
color6  #bccbb0
color7  #e1e4da

# Bright Colors
color8  #373a33
color9  #ffb4ab
color10 #a8d292
color11 #a0cfd0
color12 #c3efac
color13 #d8e7cb 
color14 #bccbb0
color15 #e1e4da
