[config]

#[config.wallpaper]
#command = "swww"
#arguments = ["img", "--transition-type", "any", "--transition-fps", "60"]
#set = true

[templates.waybar]
input_path = "~/om-works/omnix-config/home/matugen/templates/colors.css"
output_path = "~/om-works/omnix-config/home/programs/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.kitty]
input_path = "~/om-works/omnix-config/home/matugen/templates/kitty-colors.conf"
output_path = "~/om-works/omnix-config/home/programs/kitty/colors.conf"
post_hook = "kill -SIGUSR1 $(pidof kitty)"

[templates.hyprland]
input_path = "~/om-works/omnix-config/home/matugen/templates/hyprland-colors.conf"
output_path = "~/om-works/omnix-config/home/hypr/colors.conf"
post_hook = "hyprctl reload"

[templates.gtk3]
input_path = "~/om-works/omnix-config/home/matugen/templates/gtk-colors.css"
output_path = "~/om-works/omnix-config/home/programs/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "~/om-works/omnix-config/home/matugen/templates/gtk-colors.css"
output_path = "~/om-works/omnix-config/home/programs/gtk-4.0/colors.css"

[templates.rofi]
input_path = "~/om-works/omnix-config/home/matugen/templates/rofi-colors.rasi"
output_path = "~/om-works/omnix-config/home/programs/rofi/colors.rasi"

[templates.cava]
input_path = "~/om-works/omnix-config/home/matugen/templates/matugen-cava"
output_path = "~/om-works/omnix-config/home/programs/cava/config"

[templates.spicetify]
input_path = "~/om-works/omnix-config/home/matugen/templates/spotify-colors.ini"
output_path = "~/om-works/omnix-config/home/programs/spicetify/Themes/text/color.ini"

[templates.vesktop]
input_path = "~/om-works/omnix-config/home/matugen/templates/midnight-discord.css"
output_path = "~/om-works/omnix-config/home/programs/vesktop/themes/matugen.css"

[templates.nvim]
input_path = "~/om-works/omnix-config/home/matugen/templates/nvim-colors.lua"
output_path = "~/om-works/omnix-config/home/programs/nvim/lua/matugen/colors.lua"
post_hook = "nvim --headless -c 'lua require(\"matugen.colors\")()' -c qa"