# LAYER RULES
layerrule = blur, waybar
layerrule = ignorealpha 0.5, waybar
layerrule = ignorealpha 0.5, notif*
layerrule = blur, logout_dialog

# SWAYNC BLUR & XRAY
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window

layerrule = ignorealpha 1, swaync-control-center
layerrule = ignorealpha 1, swaync-notification-window

layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window
layerrule = xray 0, swaync-control-center
layerrule = xray 0, swaync-notification-window

# APPLICATIONS BLUR
windowrulev2 = noblur, tag:multimedia_video*
windowrulev2 = opacity 1.0, tag:multimedia_video*
windowrulev2 = opacity 0.8, tag:settings*
windowrulev2 = opacity 0.8, class:^(org.gnome.Nautilus)$
windowrulev2 = opacity 0.9, class:^(gedit|org.gnome.TextEditor|mousepad)$
windowrulev2 = opacity 0.9, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = opacity 0.9, class:^(kitty)$

# Opacity takes standard format: opacity <active> <inactive> <fullscreen>
windowrulev2 = opacity 0.85 0.7 1.0, class:^(discord|vesktop|org.telegram.desktop)$
windowrulev2 = opacity 0.8 0.6 1.0, class:^(Spotify)$
windowrulev2 = opacity 0.9 0.7 1.0, class:^(zen)$

# FLOAT
windowrulev2 = float, tag:settings*
windowrulev2 = float, tag:viewer*
windowrulev2 = float, tag:multimedia_video*
windowrulev2 = size 900 506, tag:multimedia_video*
windowrulev2 = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = size 50% 60%, class:^(org.pulseaudio.pavucontrol)$

# Ignore maximize requests
windowrulev2 = suppressevent maximize, class:.*

# Standard nofocus syntax
windowrulev2 = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

# POP UPS AND DIALOGUES
windowrulev2 = float, title:^(Save As|Save a File|Pick Files)$
windowrulev2 = size 50% 60%, title:^(Save As|Save a File|Pick Files)$
windowrulev2 = center, title:^(Save As|Save a File|Pick Files)$

windowrulev2 = float, initialTitle:^(Open Files)$
windowrulev2 = size 70% 60%, initialTitle:^(Open Files)$

# Waypaper rule
windowrulev2 = float, class:^(waypaper)$
windowrulev2 = size 900 600, class:^(waypaper)$
windowrulev2 = opacity 0.85 0.85, class:^(waypaper)$
windowrulev2 = center, class:^(waypaper)$