################
### MONITORS ###
################
monitor=,preferred,auto,1

###################
### MY PROGRAMS ###
###################
$terminal = kitty
$fileManager = kitty -e yazi
$menu = rofi -show drun

#############################
### ENVIRONMENT VARIABLES ###
#############################
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

#####################
### GENERAL LAYOUT ###
#####################
general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2
    layout = dwindle
}

#########################
### LOAD OTHER CONFIGS ###
#########################
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/autostart.conf
