decoration {
    rounding = 10

    blur {
        enabled = true
        size = 3
        passes = 1
    }
}

general {
    col.active_border = rgba(33ccffee)
    col.inactive_border = rgba(595959aa)
}
