################
### MONITORS ###
################
monitor = HDMI-A-5,1920x1080@100,0x0,1

####################
### COLOR SOURCE ###
####################
source = ~/.config/hypr/colors.conf

###################
### MY PROGRAMS ###
###################
$terminal = kitty
$fileManager = kitty -e yazi
$menu = rofi -show drun

#####################
### AUTOSTART ###
#####################
exec-once = nm-applet
exec-once = waybar
exec-once = swww-daemon
exec-once = blueman-applet
exec-once = swaync
exec-once = hypridle
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

#############################
### ENVIRONMENT VARIABLES ###
#############################
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

#####################
### LAYOUT ###
#####################
general {
    gaps_in = 3
    gaps_out = 6
    border_size = 2
    col.active_border = $outline
    col.inactive_border = $outline_variant
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    vfr = true
}

render {
    new_render_scheduling = true
}

#########################
### LOAD OTHER CONFIGS ###
#########################
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/windowrules.conf