# LAYER RULES
layerrule = blur, waybar
layerrule = ignorealpha 0.5, waybar
layerrule = blur, logout_dialog
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window
layerrule = xray 0, swaync-control-center
layerrule = xray 0, swaync-notification-window

# WINDOW OPACITY
windowrule = opacity 0.9, class:^(kitty)$
windowrule = opacity 0.9, class:^(org.pulseaudio.pavucontrol)$
windowrule = opacity 0.85, class:^(discord|vesktop)$

# FLOAT
windowrule = float, class:^(org.pulseaudio.pavucontrol)$
windowrule = size 50% 60%, class:^(org.pulseaudio.pavucontrol)$
windowrule = suppressevent maximize, class:.*

# POPUPS AND DIALOGUES
windowrule = float, title:^(Save As|Save a File|Pick Files)$
windowrule = size 50% 60%, title:^(Save As|Save a File|Pick Files)$
windowrule = center, title:^(Save As|Save a File|Pick Files)$
windowrule = float, initialtitle:(Open Files)
windowrule = size 70% 60%, initialtitle:(Open Files)
