-- yazi/init.lua
-- omnix-config — yazi plugins init
-- Note: git plugin requires yazi 26.1.22+
-- Current nixpkgs version is 25.5.31
-- Uncomment when yazi is updated in nixpkgs
-- require("git"):setup()
